2025-03-28 20:26:19,076 INFO    MainThread:2889633 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-28 20:26:19,076 INFO    MainThread:2889633 [wandb_setup.py:_flush():67] Configure stats pid to 2889633
2025-03-28 20:26:19,076 INFO    MainThread:2889633 [wandb_setup.py:_flush():67] Loading settings from /home/toprak/.config/wandb/settings
2025-03-28 20:26:19,076 INFO    MainThread:2889633 [wandb_setup.py:_flush():67] Loading settings from /home/toprak/PycharmProjects/cmpe591/Cmpe-591-HW3/src/wandb/settings
2025-03-28 20:26:19,076 INFO    MainThread:2889633 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-28 20:26:19,076 INFO    MainThread:2889633 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/toprak/PycharmProjects/cmpe591/Cmpe-591-HW3/src/wandb/run-20250328_202619-o63p28ex/logs/debug.log
2025-03-28 20:26:19,076 INFO    MainThread:2889633 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/toprak/PycharmProjects/cmpe591/Cmpe-591-HW3/src/wandb/run-20250328_202619-o63p28ex/logs/debug-internal.log
2025-03-28 20:26:19,076 INFO    MainThread:2889633 [wandb_init.py:init():761] calling init triggers
2025-03-28 20:26:19,076 INFO    MainThread:2889633 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-28 20:26:19,076 INFO    MainThread:2889633 [wandb_init.py:init():784] starting backend
2025-03-28 20:26:19,076 INFO    MainThread:2889633 [wandb_init.py:init():788] sending inform_init request
2025-03-28 20:26:19,077 INFO    MainThread:2889633 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-28 20:26:19,078 INFO    MainThread:2889633 [wandb_init.py:init():798] backend started and connected
2025-03-28 20:26:19,078 INFO    MainThread:2889633 [wandb_init.py:init():891] updated telemetry
2025-03-28 20:26:19,081 INFO    MainThread:2889633 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-28 20:26:19,396 ERROR   MainThread:2889633 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/home/toprak/miniforge3/envs/cmpe591/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toprak/miniforge3/envs/cmpe591/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404: {"data":{"upsertBucket":null},"errors":[{"message":"entity cmpe591 not found during upsertBucket","path":["upsertBucket"]}]}
2025-03-28 20:26:20,397 INFO    MsgRouterThr:2889633 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
