2025-03-28 20:34:14,615 INFO    MainThread:2930930 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-28 20:34:14,615 INFO    MainThread:2930930 [wandb_setup.py:_flush():67] Configure stats pid to 2930930
2025-03-28 20:34:14,615 INFO    MainThread:2930930 [wandb_setup.py:_flush():67] Loading settings from /home/toprak/.config/wandb/settings
2025-03-28 20:34:14,615 INFO    MainThread:2930930 [wandb_setup.py:_flush():67] Loading settings from /home/toprak/PycharmProjects/cmpe591/Cmpe-591-HW3/src/wandb/settings
2025-03-28 20:34:14,615 INFO    MainThread:2930930 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-28 20:34:14,615 INFO    MainThread:2930930 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/toprak/PycharmProjects/cmpe591/Cmpe-591-HW3/src/wandb/run-20250328_203414-h5nz0xhw/logs/debug.log
2025-03-28 20:34:14,615 INFO    MainThread:2930930 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/toprak/PycharmProjects/cmpe591/Cmpe-591-HW3/src/wandb/run-20250328_203414-h5nz0xhw/logs/debug-internal.log
2025-03-28 20:34:14,615 INFO    MainThread:2930930 [wandb_init.py:init():761] calling init triggers
2025-03-28 20:34:14,615 INFO    MainThread:2930930 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-28 20:34:14,615 INFO    MainThread:2930930 [wandb_init.py:init():784] starting backend
2025-03-28 20:34:14,615 INFO    MainThread:2930930 [wandb_init.py:init():788] sending inform_init request
2025-03-28 20:34:14,617 INFO    MainThread:2930930 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-28 20:34:14,617 INFO    MainThread:2930930 [wandb_init.py:init():798] backend started and connected
2025-03-28 20:34:14,617 INFO    MainThread:2930930 [wandb_init.py:init():891] updated telemetry
2025-03-28 20:34:14,619 INFO    MainThread:2930930 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-28 20:34:14,946 ERROR   MainThread:2930930 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/home/toprak/miniforge3/envs/cmpe591/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toprak/miniforge3/envs/cmpe591/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403: {"data":{"upsertBucket":null},"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}]}
2025-03-28 20:34:15,947 INFO    MsgRouterThr:2930930 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
